# Generated by Django 5.2.13 on 2026-04-19 01:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BabyCondition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("icon", models.CharField(default="👶", max_length=10)),
                ("order", models.IntegerField(default=0)),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="Remedy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("duration_minutes", models.IntegerField(blank=True, null=True)),
                ("gif_url", models.URLField(blank=True)),
                ("order", models.IntegerField(default=0)),
                (
                    "condition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="remedies",
                        to="remedies.babycondition",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Remedies",
                "ordering": ["order", "id"],
            },
        ),
    ]
