# Generated by Django 5.2.13 on 2026-04-25 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoattributes',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='videoattributes',
            name='title',
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
