# Generated by Django 5.2.13 on 2026-04-19 01:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                ("phone", models.CharField(db_index=True, max_length=20, unique=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("mother", "Mother"),
                            ("partner", "Partner"),
                            ("admin", "Admin"),
                        ],
                        default="mother",
                        max_length=20,
                    ),
                ),
                ("support_person_name", models.CharField(blank=True, max_length=200)),
                ("support_person_phone", models.CharField(blank=True, max_length=20)),
                ("ob_name", models.CharField(blank=True, max_length=200)),
                ("ob_phone", models.CharField(blank=True, max_length=20)),
                ("ob_email", models.EmailField(blank=True, max_length=254)),
                ("baby_due_date", models.DateField(blank=True, null=True)),
                ("baby_birth_date", models.DateField(blank=True, null=True)),
                ("biometric_enabled", models.BooleanField(default=False)),
                ("push_notifications_enabled", models.BooleanField(default=True)),
                (
                    "unique_code",
                    models.CharField(blank=True, max_length=16, null=True, unique=True),
                ),
                ("is_staff", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "partner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="linked_mothers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
