services:

  api:
    build:
      context: .
      dockerfile: docker/Dockerfile.api
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=mumaid.settings.prod
    restart: always


# Uncomment worker + beat when we have a paid plan:
#
#  worker:
#    build:
#      context: .
#      dockerfile: docker/Dockerfile.worker
#    command: ./start-worker.sh
#    env_file:
#      - .env
#    environment:
#      - DJANGO_SETTINGS_MODULE=mumaid.settings.prod
#      - CELERY_CONCURRENCY=2
#    restart: always
#
#  beat:
#    build:
#      context: .
#      dockerfile: docker/Dockerfile.worker
#    command: ./start-beat.sh
#    env_file:
#      - .env
#    environment:
#      - DJANGO_SETTINGS_MODULE=mumaid.settings.prod
#    restart: always