# Generated by Django 5.2.13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("opportunities", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="opportunityinterest",
            name="contact_preference",
            field=models.CharField(
                blank=True,
                default="",
                help_text="e.g. email, phone, app — how the user prefers follow-up.",
                max_length=64,
            ),
        ),
    ]
