# Generated by Django 5.2.13 on 2026-04-30 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnertaskcompletion',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
