# Generated by Django 5.2.14 on 2026-06-05 11:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mumtalk', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mumtalkpost',
            name='user',
        ),
        migrations.AddField(
            model_name='mumtalkpost',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mumtalks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mumtalkpost',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mumtalkpost',
            name='content',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='mumtalkpost',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
