# Generated by Django 5.2.13 on 2026-05-04 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('mother', 'MOTHER'), ('partner', 'PARTNER'), ('admin', 'Admin')], default='mother', max_length=20),
        ),
    ]
